### ISSUE TITLE
missing field `gasLimitBoundDivisor`

### ISSUE THREAD

**Issue by fALKENdk** [acuity-network/mix-blockchain#1]
When running `parity --chain mix.json --port 30313 --jsonrpc-port 8645 --geth` as specified in https://docs.mix-blockchain.org/en/latest/configuration.html#configuration i get the following error:

Spec json is invalid: missing field `gasLimitBoundDivisor` at line 44 column 3

**Comment by ethernomad** [comment]
Fixed!
